application:
  name: zilani
  home: ZILANI_HOME

server:
  servlet:
    register-default-servlet: true
  port: 8018
  ssl:
    enabled: false
    key-store: 'classpath:cert.p12'
    key-store-password: Ant&Ele@420
    key-store-type: PKCS12

  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json,application/xml
  connection-timeout: -1
  tomcat:
    max-http-post-size: 10485760

spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/zilani
    username: postgres
    password: zahid7292

  servlet:
    multipart:
      max-file-size: 25MB
      max-request-size: 100MB

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        show_sql: false
        dialect: org.hibernate.dialect.PostgreSQL94Dialect
        jdbc:
          lob:
            non_contextual_creation: true
          batch_size: 20
          order_inserts: true
          order_updates: true

  #  mail:
  #    protocol: smtp
  #    test-connection: false
  #    host: smtp.office365.com
  #    port: 587
  #    from: excellence@cieltextile.com
  #    username: excellence@cieltextile.com
  #    password: Yof69012
  #    properties:
  #      mail:
  #        smtp:
  #          auth: true
  #          starttls:
  #            enable: true
  mail:
    protocol: smtp
    test-connection: false
    host: smtp.gmail.com
    port: 587
    from: noreply@jaza-soft.com
    username: admin@jaza-soft.com
    password: arcutfrsuoduyivy<remove>
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true


  security:
    jwt:
      key-store: 'classpath:authServer.jks'
      key-store-password: AntEle@819
      key-pair-alias: authServer
      key-pair-password: AntEle@819
      public-key: 'classpath:public.txt'

  liquibase:
    enabled: true
    change-log: 'classpath:/db/changelog-master.xml'
#    rollback-file: '/Users/razamd/Projects/JazaSoft/apps/cfea/container/rollback-sql/rollback-sql-temp.sql'

