years: 2019,2020,2021,2022,2023
active-year: 2023
runner-up-count: 5
factories:
  - Knitting
  - Dyeing
  - Finishing
  - Carding & Spinning
  - Aquarelle Grand Bois
  - Aquarelle Tana
  - Aquarelle Antsirabe
  - Laguna Mauritius
  - Laguna Madagascar - Antsirabe
  - AIPL 2 - Bannerghatta
  - AIPL 6 - RCC
  - AIPL 7 - Samudra
  - Laguna Kanakapura
  - Tropic Reunion
  - Tropic Tana
  - Tropic Coimbatore
  - Floreal Madagascar - Antsirabe
  - Floreal Madagascar - Tana
  - Floreal Bangladesh

### Jaza Software ###
office365:
  tenantId: b0091936-1042-4ad1-abdb-1d2d8314bea1
  clientId: e94498aa-5103-45ea-a6be-b8089e4f3c3c
  clientSecret: Hi58Q~wU~.ff-xkyGKn_H5zqwxfzc5viG9a3-ano
  userId: 77ff0df8-9383-48ec-8f2d-8fdacebfa174

## Ciel Textile ###
#office365:
#  tenantId: 043ef009-8910-4384-9ee9-7902e4fbdd05
#  clientId: 49d3d0c0-1e78-456b-976f-a04bc523ab2b
#  clientSecret: ATM8Q~_v3omBQmlqZyJrlCJq4XjErKA4U2QvOdnQ
#  userId: e03d6a45-f40b-49e4-ad00-4e538752745a

## Aquarelle Office 365
#office365:
#  tenantId: 043ef009-8910-4384-9ee9-7902e4fbdd05
#  clientId: 49d3d0c0-1e78-456b-976f-a04bc523ab2b
#  clientSecret: q1c7Q~ZXMCun2UkCa5sRcya8FDJAQRa.V545K
#  userId: e03d6a45-f40b-49e4-ad00-4e538752745a

sms-server:
  headers:
  params:
    method: sms.normal
    api_key: a95e025d0fb117c091a824a27a7af65547102448
    sender: JAZASW
  enabled: true
  url: http://alerts.variforrm.in/api
configuration:
  settings:
    - !com.jazasoft.embedded.dto.Setting
      name: Factory Open Time
      dataType: number
      description: ""
      groupId: default
      key: factory-open-time
      roles: super_user,admin
      serialNo: 1
      unit: ""
      value: 08:45
  groups:
    - !com.jazasoft.embedded.dto.ConfigGroup
      id: default
      name: Default