sms-server:
  headers:
  params:
    method: sms.normal
    api_key: a95e025d0fb117c091a824a27a7af65547102448
    sender: JAZASW
  enabled: true
  url: http://alerts.variforrm.in/api
configuration:
  settings:
    - !com.jazasoft.embedded.dto.Setting
      name: Factory Open Time
      dataType: number
      description: ""
      groupId: default
      key: factory-open-time
      roles: super_user,admin
      serialNo: 1
      unit: ""
      value: 08:45
  groups:
    - !com.jazasoft.embedded.dto.ConfigGroup
      id: default
      name: Default